name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build . -t weaaves1/my-app:latest

      - name: Run tests
        run: |
          echo "Running tests..."

      - name: Heroku Login
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: devops4
          docker_image: weaaves1/my-app:latest

      - name: Push Docker image to Heroku
        run: |
          heroku container:push web --app devops4
          heroku container:release web --app devops4
